version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: test
    restart: always
    environment:
      POSTGRES_USER: shakib
      POSTGRES_PASSWORD: azad22azad22
      POSTGRES_DB: nest
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestapp:
    build: .
    container_name: nest-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      .env.docker
    depends_on:
      - postgres

volumes:
  pgdata: